[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=45",
    "wheel",
    "setuptools_scm>=6.2",
]

[tool.setuptools_scm]
version_scheme = "python-simplified-semver"

